/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as EftsIndexRouteImport } from './routes/efts.index'
import { Route as EftsIdRouteImport } from './routes/efts.$id'
import { Route as AccountsIdRouteImport } from './rou./routes/accounts.$id
import { Route as SectorsIdChartRouteImport } from './routes/sectors.$id.chart'
import { Route as EftsIdTableRouteImport } from './routes/efts.$id.table'
import { Route as EftsIdSignalsRouteImport } from './routes/efts.$id.signals'
import { Route as EftsIdChartWebgpuRouteImport } from './routes/efts.$id.chart-webgpu'
import { Route as EftsIdChartRouteImport } from './routes/efts.$id.chart'
import { Route as AccountsIdTransactionsRouteImport } from './routes/accounts.$id.transactions'
import { Route as AccountsIdHoldingsRouteImport } from './routes/accounts.$id.holdings'
import { Route as AccountsIdTransactionsTxidRouteImport } from './routes/accounts.$id.transactions.$txid'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIndexRoute = EftsIndexRouteImport.update({
  id: '/efts/',
  path: '/efts/',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIdRoute = EftsIdRouteImport.update({
  id: '/efts/$id',
  path: '/efts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const SectorsIdChartRoute = SectorsIdChartRouteImport.update({
  id: '/sectors/$id/chart',
  path: '/sectors/$id/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIdTableRoute = EftsIdTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdSignalsRoute = EftsIdSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdChartWebgpuRoute = EftsIdChartWebgpuRouteImport.update({
  id: '/chart-webgpu',
  path: '/chart-webgpu',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdChartRoute = EftsIdChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => EftsIdRoute,
} as any)
const AccountsIdTransactionsRoute = AccountsIdTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AccountsIdRoute,
} as any)
const AccountsIdHoldingsRoute = AccountsIdHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AccountsIdRoute,
} as any)
const AccountsIdTransactionsTxidRoute =
  AccountsIdTransactionsTxidRouteImport.update({
    id: '/$txid',
    path: '/$txid',
    getParentRoute: () => AccountsIdTransactionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/efts': typeof EftsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/accounts/$id/holdings': typeof AccountsIdHoldingsRoute
  '/accounts/$id/transactions': typeof AccountsIdTransactionsRouteWithChildren
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
  '/accounts/$id/transactions/$txid': typeof AccountsIdTransactionsTxidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/efts': typeof EftsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/accounts/$id/holdings': typeof AccountsIdHoldingsRoute
  '/accounts/$id/transactions': typeof AccountsIdTransactionsRouteWithChildren
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
  '/accounts/$id/transactions/$txid': typeof AccountsIdTransactionsTxidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/search': typeof SearchRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/efts/': typeof EftsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/accounts/$id/holdings': typeof AccountsIdHoldingsRoute
  '/accounts/$id/transactions': typeof AccountsIdTransactionsRouteWithChildren
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
  '/accounts/$id/transactions/$txid': typeof AccountsIdTransactionsTxidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/search'
    | '/accounts/$id'
    | '/efts/$id'
    | '/efts'
    | '/sectors'
    | '/accounts/$id/holdings'
    | '/accounts/$id/transactions'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
    | '/accounts/$id/transactions/$txid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/search'
    | '/accounts/$id'
    | '/efts/$id'
    | '/efts'
    | '/sectors'
    | '/accounts/$id/holdings'
    | '/accounts/$id/transactions'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
    | '/accounts/$id/transactions/$txid'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/search'
    | '/accounts/$id'
    | '/efts/$id'
    | '/efts/'
    | '/sectors/'
    | '/accounts/$id/holdings'
    | '/accounts/$id/transactions'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
    | '/accounts/$id/transactions/$txid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  AiRoute: typeof AiRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  SearchRoute: typeof SearchRoute
  EftsIdRoute: typeof EftsIdRouteWithChildren
  EftsIndexRoute: typeof EftsIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
  SectorsIdChartRoute: typeof SectorsIdChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/': {
      id: '/efts/'
      path: '/efts'
      fullPath: '/efts'
      preLoaderRoute: typeof EftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/$id': {
      id: '/efts/$id'
      path: '/efts/$id'
      fullPath: '/efts/$id'
      preLoaderRoute: typeof EftsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/sectors/$id/chart': {
      id: '/sectors/$id/chart'
      path: '/sectors/$id/chart'
      fullPath: '/sectors/$id/chart'
      preLoaderRoute: typeof SectorsIdChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/$id/table': {
      id: '/efts/$id/table'
      path: '/table'
      fullPath: '/efts/$id/table'
      preLoaderRoute: typeof EftsIdTableRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/signals': {
      id: '/efts/$id/signals'
      path: '/signals'
      fullPath: '/efts/$id/signals'
      preLoaderRoute: typeof EftsIdSignalsRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/chart-webgpu': {
      id: '/efts/$id/chart-webgpu'
      path: '/chart-webgpu'
      fullPath: '/efts/$id/chart-webgpu'
      preLoaderRoute: typeof EftsIdChartWebgpuRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/chart': {
      id: '/efts/$id/chart'
      path: '/chart'
      fullPath: '/efts/$id/chart'
      preLoaderRoute: typeof EftsIdChartRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/accounts/$id/transactions': {
      id: '/accounts/$id/transactions'
      path: '/transactions'
      fullPath: '/accounts/$id/transactions'
      preLoaderRoute: typeof AccountsIdTransactionsRouteImport
      parentRoute: typeof AccountsIdRoute
    }
    '/accounts/$id/holdings': {
      id: '/accounts/$id/holdings'
      path: '/holdings'
      fullPath: '/accounts/$id/holdings'
      preLoaderRoute: typeof AccountsIdHoldingsRouteImport
      parentRoute: typeof AccountsIdRoute
    }
    '/accounts/$id/transactions/$txid': {
      id: '/accounts/$id/transactions/$txid'
      path: '/$txid'
      fullPath: '/accounts/$id/transactions/$txid'
      preLoaderRoute: typeof AccountsIdTransactionsTxidRouteImport
      parentRoute: typeof AccountsIdTransactionsRoute
    }
  }
}

interface AccountsIdTransactionsRouteChildren {
  AccountsIdTransactionsTxidRoute: typeof AccountsIdTransactionsTxidRoute
}

const AccountsIdTransactionsRouteChildren: AccountsIdTransactionsRouteChildren =
  {
    AccountsIdTransactionsTxidRoute: AccountsIdTransactionsTxidRoute,
  }

const AccountsIdTransactionsRouteWithChildren =
  AccountsIdTransactionsRoute._addFileChildren(
    AccountsIdTransactionsRouteChildren,
  )

interface AccountsIdRouteChildren {
  AccountsIdHoldingsRoute: typeof AccountsIdHoldingsRoute
  AccountsIdTransactionsRoute: typeof AccountsIdTransactionsRouteWithChildren
}

const AccountsIdRouteChildren: AccountsIdRouteChildren = {
  AccountsIdHoldingsRoute: AccountsIdHoldingsRoute,
  AccountsIdTransactionsRoute: AccountsIdTransactionsRouteWithChildren,
}

const AccountsIdRouteWithChildren = AccountsIdRoute._addFileChildren(
  AccountsIdRouteChildren,
)

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRouteWithChildren
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRouteWithChildren,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface EftsIdRouteChildren {
  EftsIdChartRoute: typeof EftsIdChartRoute
  EftsIdChartWebgpuRoute: typeof EftsIdChartWebgpuRoute
  EftsIdSignalsRoute: typeof EftsIdSignalsRoute
  EftsIdTableRoute: typeof EftsIdTableRoute
}

const EftsIdRouteChildren: EftsIdRouteChildren = {
  EftsIdChartRoute: EftsIdChartRoute,
  EftsIdChartWebgpuRoute: EftsIdChartWebgpuRoute,
  EftsIdSignalsRoute: EftsIdSignalsRoute,
  EftsIdTableRoute: EftsIdTableRoute,
}

const EftsIdRouteWithChildren =
  EftsIdRoute._addFileChildren(EftsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  AiRoute: AiRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  SearchRoute: SearchRoute,
  EftsIdRoute: EftsIdRouteWithChildren,
  EftsIndexRoute: EftsIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
  SectorsIdChartRoute: SectorsIdChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
