/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as HoldingsRouteImport } from './routes/holdings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as SectorsIndexRouteImport } from './routes/sectors.index'
import { Route as EftsIndexRouteImport } from './routes/efts.index'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as EftsIdRouteImport } from './routes/efts.$id'
import { Route as SectorsIdChartRouteImport } from './routes/sectors.$id.chart'
import { Route as EftsIdTableRouteImport } from './routes/efts.$id.table'
import { Route as EftsIdSignalsRouteImport } from './routes/efts.$id.signals'
import { Route as EftsIdChartWebgpuRouteImport } from './routes/efts.$id.chart-webgpu'
import { Route as EftsIdChartRouteImport } from './routes/efts.$id.chart'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HoldingsRoute = HoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIndexRoute = SectorsIndexRouteImport.update({
  id: '/sectors/',
  path: '/sectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIndexRoute = EftsIndexRouteImport.update({
  id: '/efts/',
  path: '/efts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIdRoute = EftsIdRouteImport.update({
  id: '/efts/$id',
  path: '/efts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsIdChartRoute = SectorsIdChartRouteImport.update({
  id: '/sectors/$id/chart',
  path: '/sectors/$id/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const EftsIdTableRoute = EftsIdTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdSignalsRoute = EftsIdSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdChartWebgpuRoute = EftsIdChartWebgpuRouteImport.update({
  id: '/chart-webgpu',
  path: '/chart-webgpu',
  getParentRoute: () => EftsIdRoute,
} as any)
const EftsIdChartRoute = EftsIdChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => EftsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/search': typeof SearchRoute
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/efts': typeof EftsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/search': typeof SearchRoute
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/efts': typeof EftsIndexRoute
  '/sectors': typeof SectorsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/holdings': typeof HoldingsRoute
  '/search': typeof SearchRoute
  '/efts/$id': typeof EftsIdRouteWithChildren
  '/transactions/$id': typeof TransactionsIdRoute
  '/efts/': typeof EftsIndexRoute
  '/sectors/': typeof SectorsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/efts/$id/chart': typeof EftsIdChartRoute
  '/efts/$id/chart-webgpu': typeof EftsIdChartWebgpuRoute
  '/efts/$id/signals': typeof EftsIdSignalsRoute
  '/efts/$id/table': typeof EftsIdTableRoute
  '/sectors/$id/chart': typeof SectorsIdChartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/holdings'
    | '/search'
    | '/efts/$id'
    | '/transactions/$id'
    | '/efts'
    | '/sectors'
    | '/transactions'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/holdings'
    | '/search'
    | '/efts/$id'
    | '/transactions/$id'
    | '/efts'
    | '/sectors'
    | '/transactions'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/compare'
    | '/dashboard'
    | '/holdings'
    | '/search'
    | '/efts/$id'
    | '/transactions/$id'
    | '/efts/'
    | '/sectors/'
    | '/transactions/'
    | '/efts/$id/chart'
    | '/efts/$id/chart-webgpu'
    | '/efts/$id/signals'
    | '/efts/$id/table'
    | '/sectors/$id/chart'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  HoldingsRoute: typeof HoldingsRoute
  SearchRoute: typeof SearchRoute
  EftsIdRoute: typeof EftsIdRouteWithChildren
  TransactionsIdRoute: typeof TransactionsIdRoute
  EftsIndexRoute: typeof EftsIndexRoute
  SectorsIndexRoute: typeof SectorsIndexRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  SectorsIdChartRoute: typeof SectorsIdChartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holdings': {
      id: '/holdings'
      path: '/holdings'
      fullPath: '/holdings'
      preLoaderRoute: typeof HoldingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/': {
      id: '/sectors/'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/': {
      id: '/efts/'
      path: '/efts'
      fullPath: '/efts'
      preLoaderRoute: typeof EftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/$id': {
      id: '/efts/$id'
      path: '/efts/$id'
      fullPath: '/efts/$id'
      preLoaderRoute: typeof EftsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$id/chart': {
      id: '/sectors/$id/chart'
      path: '/sectors/$id/chart'
      fullPath: '/sectors/$id/chart'
      preLoaderRoute: typeof SectorsIdChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/efts/$id/table': {
      id: '/efts/$id/table'
      path: '/table'
      fullPath: '/efts/$id/table'
      preLoaderRoute: typeof EftsIdTableRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/signals': {
      id: '/efts/$id/signals'
      path: '/signals'
      fullPath: '/efts/$id/signals'
      preLoaderRoute: typeof EftsIdSignalsRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/chart-webgpu': {
      id: '/efts/$id/chart-webgpu'
      path: '/chart-webgpu'
      fullPath: '/efts/$id/chart-webgpu'
      preLoaderRoute: typeof EftsIdChartWebgpuRouteImport
      parentRoute: typeof EftsIdRoute
    }
    '/efts/$id/chart': {
      id: '/efts/$id/chart'
      path: '/chart'
      fullPath: '/efts/$id/chart'
      preLoaderRoute: typeof EftsIdChartRouteImport
      parentRoute: typeof EftsIdRoute
    }
  }
}

interface EftsIdRouteChildren {
  EftsIdChartRoute: typeof EftsIdChartRoute
  EftsIdChartWebgpuRoute: typeof EftsIdChartWebgpuRoute
  EftsIdSignalsRoute: typeof EftsIdSignalsRoute
  EftsIdTableRoute: typeof EftsIdTableRoute
}

const EftsIdRouteChildren: EftsIdRouteChildren = {
  EftsIdChartRoute: EftsIdChartRoute,
  EftsIdChartWebgpuRoute: EftsIdChartWebgpuRoute,
  EftsIdSignalsRoute: EftsIdSignalsRoute,
  EftsIdTableRoute: EftsIdTableRoute,
}

const EftsIdRouteWithChildren =
  EftsIdRoute._addFileChildren(EftsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  HoldingsRoute: HoldingsRoute,
  SearchRoute: SearchRoute,
  EftsIdRoute: EftsIdRouteWithChildren,
  TransactionsIdRoute: TransactionsIdRoute,
  EftsIndexRoute: EftsIndexRoute,
  SectorsIndexRoute: SectorsIndexRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  SectorsIdChartRoute: SectorsIdChartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
