/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Page3RouteImport } from './routes/page3'
import { Route as Page2RouteImport } from './routes/exchanges'
import { Route as IndexRouteImport } from './ro./routes/exchanges/exchanges

const Page3Route = Page3RouteImport.update({./routes./routes/efts.indexnges.indexsactions/transactions.$transactionId
  id: '/page3',./routes/transactions.index
  path: '/page3',./routes/exchanges/$exchangeId/$exchangeId./routes/exchanges/$exchangeId/exchanges.$exchangeId.index
  getParentRoute: () => rootRouteImport,
} as any)./routes/efts.$id.chart
const Page2Route = Page2RouteImport.update({
  id: '/page2',
  path: '/page2',./routes/efts.$id.chart-webgpu
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/page3': typeof Page3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/page3': typeof Page3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/page2': typeof Page2Route
  '/page3': typeof Page3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page2' | '/page3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page2' | '/page3'
  id: '__root__' | '/' | '/page2' | '/page3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Page2Route: typeof Page2Route
  Page3Route: typeof Page3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/page3': {
      id: '/page3'
      path: '/page3'
      fullPath: '/page3'
      preLoaderRoute: typeof Page3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page2': {
      id: '/page2'
      path: '/page2'
      fullPath: '/page2'
      preLoaderRoute: typeof Page2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Page2Route: Page2Route,
  Page3Route: Page3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
